package fr.thomasdindin.api_starter.audit;

public enum AuditAction {
    SUCCESSFUL_REGISTRATION,
    FAILED_REGISTRATION,
    SUCCESSFUL_LOGIN,
    FAILED_LOGIN,
    BLOCKED_ACCOUNT,
    LOGOUT,
    FAILED_EMAIL_VERIFICATION,
    SUCCESSFUL_EMAIL_VERIFICATION,
    RESET_PASSWORD_REQUEST,
    RESET_PASSWORD,
}